---
abstract: 'Sugar sprinkled on XML::Simple'
author:
  - 'Chris Tijerina'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Simple-Sugar
provides:
  XML::Simple::Sugar:
    file: lib/XML/Simple/Sugar.pm
    version: v1.0.5
requires:
  Data::Dumper: '0'
  Modern::Perl: '0'
  Moops: '0'
  UNIVERSAL::isa: '0'
  XML::Simple: '0'
  perl: v5.18.2
resources:
  bugtracker: https://github.com/Camspi/XML-Simple-Sugar/issues
  homepage: https://github.com/Camspi/XML-Simple-Sugar
  repository: https://github.com/Camspi/XML-Simple-Sugar.git
version: v1.0.5
x_contributors:
  - 'Camspi <amarus18@hotmail.com>'
  - 'Chris Tijerina <amarus18@hotmail.com>'
  - 'Chris Tijerina <ctijerina@emortgagelogic.com>'
